import Image from "next/image";

const android = "https://play.google.com/store/apps/details?id=com.sabil.subscriptiontracker";
const ios = "https://apps.apple.com/us/app/substracker-premium/id6773412477";

function Store({ kind, url }: { kind: "Apple" | "Google"; url: string }) {
  return <a href={url} target="_blank" rel="noreferrer" className="store"><span className="store-icon">{kind === "Apple" ? "A" : "G"}</span><span><small>{kind === "Apple" ? "Download on the" : "GET IT ON"}</small><b>{kind === "Apple" ? "App Store" : "Google Play"}</b></span></a>;
}

export default function Home() {
  return <main>
    <header className="site-header"><a className="brand" href="#top"><Image src="/favicon.png" alt="" width={42} height={42} /><span>Substracker <b>Premium</b></span></a><nav><a href="#problem">The problem</a><a href="#solution">How it works</a><a href="#technology">Technology</a></nav><a className="nav-cta" href="#download">Download app</a></header>
    <section id="top" className="hero">
      <div className="hero-copy revised-hero-copy"><div className="eyebrow">Subscription clarity, finally</div><h1>Know what you pay.<br /><em>Keep what matters.</em></h1><p>Track all your subscriptions in one place. Get renewal reminders, monitor spending, and never miss a payment again.</p><div className="store-row"><Store kind="Apple" url={ios} /><Store kind="Google" url={android} /></div></div>
      <div className="hero-art screenshot-art"><div className="orb one" /><div className="orb two" /><div className="app-shot shot-one"><Image src="/add-subscription.png" alt="Substracker add subscription screen" width={370} height={744} priority /></div><div className="app-shot shot-two"><Image src="/subscription-details.png" alt="Substracker subscription details screen" width={370} height={744} priority /></div><div className="float alert"><b>↗</b><span><small>Quick setup</small><strong>Add any subscription</strong></span></div><div className="float saved"><b>✓</b><span><small>Stay informed</small><strong>Review before renewal</strong></span></div></div>
      {/* <div className="hero-copy"><div className="eyebrow">Subscription clarity, finally</div><h1>Know what you pay.<br /><em>Keep what matters.</em></h1><p>Substracker Premium brings every recurring expense, renewal, and spending insight into one calm, beautifully simple place.</p><div className="store-row"><Store kind="Apple" url={ios} /><Store kind="Google" url={android} /></div></div> */}
      <div className="hero-art"><div className="orb one" /><div className="orb two" /><div className="float alert"><b>↗</b><span><small>Renewal reminder</small><strong>Netflix · Tomorrow</strong></span></div><div className="phone"><div className="screen"><div className="island" /><div className="status"><span>9:41</span><span>● ●●</span></div><div className="greeting"><div><small>GOOD MORNING</small><h3>Your subscriptions</h3></div><i>SP</i></div><div className="spend"><span>Monthly spend</span><strong>$84.47</strong><div className="bars">{[38,52,44,68,56,82,72,92].map((height,index)=><i key={index} style={{height:`${height}%`}} />)}</div><footer><span>6 active</span><span>$1,013 / year</span></footer></div><div className="upcoming"><b>Upcoming</b><span>See all</span></div><div className="sub"><i>N</i><div><b>Netflix</b><small>Tomorrow</small></div><strong>$15.49</strong></div><div className="sub"><i>●</i><div><b>Spotify</b><small>In 4 days</small></div><strong>$10.99</strong></div><div className="sub"><i>☁</i><div><b>Cloud storage</b><small>In 8 days</small></div><strong>$2.99</strong></div><div className="phone-nav"><span>⌂<small>Home</small></span><span>▥<small>Analytics</small></span><span>◎<small>Profile</small></span></div></div></div><div className="float saved"><b>✓</b><span><small>Annual overview</small><strong>Your full spend, clear.</strong></span></div></div>
    </section>
    <section className="ticker"><span>One clear dashboard</span><i>✦</i><span>Smart renewal reminders</span><i>✦</i><span>Private by design</span><i>✦</i><span>iOS + Android</span></section>
    <section className="section"><div className="label">01 — What is this app?</div><div className="intro-grid"><h2>Your personal command center for <em>recurring spend.</em></h2><div><p className="lead">Substracker Premium is a focused mobile app for organizing the subscriptions that quietly shape your monthly budget.</p><p>Add a service in seconds, choose its billing cycle, set reminders, and see what is coming next. From streaming and software to memberships and custom plans, everything stays visible.</p><aside><span>✓ Quick-add templates</span><span>✓ Weekly to custom billing</span><span>✓ Guest mode included</span></aside></div></div></section>
    <section id="problem" className="dark-section"><div className="section"><div className="label light-label">02 — The problem</div><div className="split"><h2>Subscriptions are easy to start.<br /><em>They are harder to see.</em></h2><p>Recurring payments are designed to disappear into the background. That is convenient—until the charges add up.</p></div><div className="problem-grid"><article><span>01</span><h3>Renewals hide in plain sight</h3><p>A free trial quietly becomes a charge. An annual plan renews before you remember it exists.</p></article><article><span>02</span><h3>Small payments become big spend</h3><p>Scattered weekly, monthly, and yearly plans make the real total almost impossible to see.</p></article><article><span>03</span><h3>Value is hard to judge</h3><p>It is difficult to decide what is useful, overpriced, or ready to cancel.</p></article></div></div></section>
    <section id="solution" className="section"><div className="label">03 — How we solve it</div><div className="split"><h2>Less money anxiety.<br /><em>More informed choices.</em></h2><p>Substracker turns scattered renewals into a simple routine: capture, understand, and act before the next charge.</p></div><div className="feature-grid"><article><b>◷</b><h3>Never miss a renewal</h3><p>Get timely push reminders before upcoming charges, including custom notification windows.</p></article><article><b>↗</b><h3>See the real cost</h3><p>Understand monthly and yearly totals, upcoming charges, and spending by category.</p></article><article><b>✦</b><h3>Review what you use</h3><p>Track usage, record value, flag overpriced plans, and keep cancellation notes.</p></article><article><b>✓</b><h3>Start without friction</h3><p>Use guest mode immediately, then sign in when you want to stay connected.</p></article></div></section>
    <section className="workflow"><div className="section workflow-grid"><div className="chart-card"><div className="insight"><header><div><small>YEARLY ESTIMATE</small><strong>$1,013.64</strong></div><span>12 mo</span></header><main><div className="donut"><span>$84<small>/mo</small></span></div><ul><li>Entertainment <b>44%</b></li><li>Productivity <b>31%</b></li><li>Other <b>25%</b></li></ul></main><footer>✦ Review your largest plans first.</footer></div></div><div className="steps"><div className="label">A simple habit</div><h2>From “what was that charge?” to <em>total clarity.</em></h2><ol><li><span>1</span><div><h3>Add your subscriptions</h3><p>Pick a template or enter any recurring payment with its price and schedule.</p></div></li><li><span>2</span><div><h3>Choose when to be reminded</h3><p>Set renewal alerts for the days that give you enough time to decide.</p></div></li><li><span>3</span><div><h3>Review the bigger picture</h3><p>Compare monthly, yearly, category, and upcoming spend.</p></div></li></ol></div></div></section>
    <section id="technology" className="section"><div className="label">04 — Technology</div><div className="split"><h2>Built with a modern stack.<br /><em>Designed to feel effortless.</em></h2><p>The simple experience on your screen is backed by reliable native, cloud, database, and commerce technology.</p></div><div className="tech-grid"><article><b>RN</b><div><h3>React Native</h3><p>A polished iOS and Android experience.</p></div></article><article><b>EX</b><div><h3>Expo</h3><p>Routing, notifications, secure storage, releases.</p></div></article><article><b>FB</b><div><h3>Firebase</h3><p>Dependable push renewal reminders.</p></div></article><article><b>NX</b><div><h3>Next.js</h3><p>Typed APIs for subscriptions and analytics.</p></div></article><article><b>DB</b><div><h3>PostgreSQL + Prisma</h3><p>Reliable structured product data.</p></div></article><article><b>S3</b><div><h3>AWS S3</h3><p>Scalable storage for app assets and media.</p></div></article><article><b>IAP</b><div><h3>StoreKit + Google Play</h3><p>Verified premium purchases on both stores.</p></div></article><article><b>TS</b><div><h3>TypeScript</h3><p>Safer development from mobile to API.</p></div></article></div></section>
    <section className="result"><div className="section"><div className="label light-label">05 — The result</div><div className="result-grid"><div><h2>A calmer way to make <em>every renewal intentional.</em></h2><p>The result is a small, useful system that gives you time to decide before money leaves your account.</p></div><div className="result-cards"><article><b>01</b><h3>Fewer surprises</h3><p>Know what is renewing and when.</p></article><article><b>02</b><h3>Clearer spending</h3><p>See recurring costs as one picture.</p></article><article><b>03</b><h3>Better decisions</h3><p>Keep plans that earn their place.</p></article></div></div></div></section>
    <section id="download" className="section download"><div className="download-card"><div><div className="label light-label">Ready when you are</div><h2>Put every subscription<br /><em>back in your control.</em></h2><p>Download Substracker Premium and make your next renewal an informed one.</p><div className="store-row"><Store kind="Apple" url={ios} /><Store kind="Google" url={android} /></div></div><aside><Image src="/icon.png" alt="Substracker Premium app icon" width={210} height={210} /></aside></div></section>
    <footer className="site-footer"><div className="brand"><Image src="/favicon.png" alt="" width={38} height={38} /><span>Substracker <b>Premium</b></span></div><p>Track less. Know more. Keep what matters.</p><div><a href={ios}>App Store</a><a href={android}>Google Play</a><span>© {new Date().getFullYear()} Substracker</span></div></footer>
  </main>;
}
